spring.application.name=apialunos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/db_apialunos
spring.datasource.username=root
spring.datasource.password=