spring.apllication.name=atividadepontuada

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/atividadePontuada1
spring.datasource.username=root
spring.datasource.password=